import "./styles/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function Home() {
  const url = "https://broken-tinted-wombat.glitch.me/bands";
  const res = await fetch(url);
  const bandData = await res.json();

  console.log(bandData);
}

return <html lang="en"></html>;
