import "./styles/globals.css";
import { Libre_Baskerville } from "next/font/google"
import Header from "@/app/components/Header";
import Footer from "@/app/components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // const url = "https://broken-tinted-wombat.glitch.me/bands";
  // const res = await fetch(url);
  // const bandData = await res.json();
  // console.log(bandData);
  {
    return (
      <html lang="en">
        <body>
          <Header></Header>
          {children}
          <Footer></Footer>
        </body>
      </html>
    );
  }
}
